### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by WeAreGeek** [GoranM/sprycle#2]
Hello,

I had problems installing this module. When installing it from file (using the master.zip), the file is successfully extracted in the scripts/addons/ folder, but it doesn't appear in the add-ons overview in user preferences.

I found out that Blender only needs the sub folder (/sprycle-master/generation/spryclegen/) containing the __init__.py file.

Maybe the documentation can be adjusted to reflect this information?

Kind regards,
Raoul

**Comment by GoranM** [comment]
I think [the documentation](https://github.com/GoranM/sprycle/wiki/Generating-cycle-data#addon-installation) already makes that clear:

> The spryclegen package is a blender add-on, which needs to be installed before it can be used. As a python package, it can be compressed into a .zip archive, for installation via blender, or it can simply be moved into the blender "scripts/addons" directory

**Comment by WeAreGeek** [comment]
You are right. I only followed the Installation section in README.md and thought I could just download the master.zip and install that as an add-on. I didn't follow the link to 'relevant info', because I assumed it pointed to general info of installing Blender add-ons.
